server:
  port: 9999

spring:
  application:
    name: VitaminCode_BE

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vitamincode_class
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

mybatis:
  config-location: classpath:/static/mybatis/mybatis-config.xml
  mapper-locations: classpath:/static/mybatis/mapper/*.xml

jwt:
  secret-key: "YHeTykc90EQL7tozCEbrLoTVpZ/PxtOQ/MyoDDfaS20k+lHHFVXyVp7vviKI9dEm"

